### ISSUE TITLE
Wrong command in section 4 of readme

### ISSUE THREAD

**Issue by zervnet** [desec-io/certbot-hook#1]
in Section 4 the command starts with certbot-auto, but it should be just certbot
(I installed certbot following the [instructions on the homepage](https://certbot.eff.org/#ubuntuxenial-other))

this wokrs for me:

         certbot --manual \
         --text \
         --preferred-challenges dns \
         --manual-auth-hook ./hook.sh \
         -d "YOURDOMAINNAME.dedyn.io" \
         certonly

**Comment by peterthomassen** [comment]
This depends on where on their page you look ;-) See https://certbot.eff.org/#ubuntuother-other

But it's true, the current phrasing is not very clear. I'll prepare a fix.
