### ISSUE TITLE
Hook-Script-Error when using certbot renew via cron 

### ISSUE THREAD

**Issue by whowantsmybigdata** [desec-io/certbot-hook#11]
Hi, 
thanks for the great service provided by deSEC! Am using it for a while and works flawlessly and very easy to handle! Naturally I donated aswell...
I've only one issue with the hook.sh for auto-renewing (via certbot and cron) my LetsEncrypt-Certs... 
My cron command is simply:
<code>/usr/bin/certbot renew</code> 
When putting the same command manually everything works as hook.sh and .dedynauth are in the same folder and have the right permissions but when cron triggers it I always get this error-message:
<code>Hook command "hook.sh" returned error code 1
Error output from hook.sh:
File /root/.dedynauth not found. Please place .dedynauth file in appropriate location.</code>
I tried to change the lines regarding the path for .dedynauth in the hook.sh but whatever I put there it always sets a "/root/" in front of the path. 
Thanks for ideas/solutions!

**Comment by peterthomassen** [comment]
The hook script looks for `.dedynauth` in the directory from which the script is run. If you run a cronjob as root, this is the `/root/` directory.

To change the directory from which the script is run, you need to change your cron command like this:
```
cd /path/to/which/you/want/to/switch/ && /usr/bin/certbot renew
```

Does this help?

**Comment by whowantsmybigdata** [comment]
Nice, thanks for the super fast reply! 
Didn't thought of that but the "cd" in cron worked!
