### ISSUE TITLE
hook.sh only working for dedyn.io domains

### ISSUE THREAD

**Issue by mocaadmin** [desec-io/certbot-hook#18]
I have a problem using the hook script with a custom domain name not ending in dedyn.io. The authorization domain name from .dedynauth is always taken also for addressing the right RRSet. The correct way in my opinion should be a substring of the variable CERTBOT_DOMAIN. See lines 75, 78, 101.
Any chance to correct this in the script if you can confirm the error?

**Comment by nils-wisiol** [comment]
We're planning to replace the hook script with an actual certbot plugin: https://github.com/desec-io/certbot-dns-desec

So, we likely won't continue development over here. Official deprecation is delayed until certbot-dns-desec is stable, though.

**Comment by peterthomassen** [comment]
Have you tried setting `DEDYN_NAME` to your custom domain?

**Comment by mocaadmin** [comment]
My use case is to update with the same .dedynauth file several domains. You are absolutely right about changing `DEDYN_NAME` but in a script it would require RW-access to the dedynauth file.
I would prefer a solution where the `RRSet` is addressed with the variable given from the hook script.
I have not checked your new certbot plugin since it still messes up my certbot (mismatch of debian repository and downloadable version).
Maybe you can remember my usecase in this certbot plugin?

**Comment by peterthomassen** [comment]
Our certbot plugin (https://github.com/desec-io/certbot-dns-desec) does support your use case. Please check out the README on that page for a how-to. The plugin should be functional starting at version v0.2.2 (will be released over the next few days).

As the plugin replaces the hook script, we are not going to add this functionality to the hook script.
