### ISSUE TITLE
[QUESTION]: Certificate Signing Request (CSR)?

### ISSUE THREAD

**Issue by ghost** [desec-io/certbot-hook#19]
Hello Folks!

How to use CSR file with desec-certbot-hook?

Regards,
RG.

**Comment by peterthomassen** [comment]
Please see https://desec.readthedocs.io/en/latest/dyndns/lets-encrypt.html.

**Comment by nils-wisiol** [comment]
Or consider using https://github.com/desec-io/certbot-dns-desec

**Comment by ghost** [comment]
@peterthomassen and @nils-wisiol 

Thanks both for the info. :)
