### ISSUE TITLE
${CERTBOT_VALIDATION} sometimes begins with hyphen, breaking grep

### ISSUE THREAD

**Issue by tofurky** [desec-io/certbot-hook#3]
i noticed that during my most recent renewal, it appears that certbot set `${CERTBOT_VALIDATION}` to a string beginning with a hyphen, e.g.: `-7aFBtiaGe8oob7quee6Oochahvahtufohcixaic8oh` (not the actual token, just the beginning `-7aFB` is real...)
this caused the grep command to error out while the hook attempted to confirm the successful creation of the TXT entry:
`grep: tiaGe8oob7quee6Oochahvahtufohcixaic8oh: invalid context length argument`
i think  the easiest way to fix this would be to add a '--' to the grep like so:
`	CURRENT=$(host -t TXT _acme-challenge.$DEDYN_NAME ns1.desec.io | grep --
 "$CERTBOT_VALIDATION")`
i'm not certain that's 100% portable across other platforms, e.g. bsd. the error occurred on linux with GNU grep.
to be clear, the challenge *did* get set correctly via the http PUT and the renewal was otherwise successful.
thanks for providing this functionality :) my experience with setting up hooks, etc. has been that it's tricky because you only can test your setup every 3 months.

**Comment by peterthomassen** [comment]
Thank you for this report! I fixed the issue as proposed by you.

Regarding Let's Encrypt testing, you can use their staging environment (https://letsencrypt.org/docs/staging-environment/).
