### ISSUE TITLE
Add "secure .dedynauth file" to instructions

### ISSUE THREAD

**Issue by rugk** [desec-io/certbot-hook#4]
IMHO just to be sure, the docs should mention to properly secure the `.dedynauth` file. I think it may be enough if root can read it, is not it? (as certbot runs as root?)

**Comment by peterthomassen** [comment]
Thanks for this suggestion! The docs belong to the `desec-static` repository. Would you mind creating a PR there? The file in question is: https://github.com/desec-io/desec-static/blob/master/app/views/docs/certbot.jade

Thanks!
